spring:
  application:
    name: shop-zuul-proxy

zuul:
  ignoredServices: "*"
  routes:
    stock-service:
      path: /product/**
      sensitiveHeaders:
      serviceId: PRODUCT-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true